<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SubkriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_subkriteria')->insert([
            // kopi robusta
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '1','range' => '2000-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '2','range' => '1750-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '3','range' => '1500-1750','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '4','range' => '<1500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '2','range' => '3000-5000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '3','range' => '3500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '4','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '1','range' => '5.3-6.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '2','range' => '6.0-6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '3','range' => '>6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '2','range' => '5.0-5.3','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '3','range' => '<5','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '2','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '3','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '4','range' => '<50','created_at' => now()],
            // kelapa sawit
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '1','range' => '1700-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '2','range' => '1450-1700','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '3','range' => '1250-1450','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '4','range' => '<1250','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '2','range' => '2500-3500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '3','range' => '3500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '4','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '1','range' => '5.0-6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '2','range' => '4.2-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '3','range' => '<7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '2','range' => '6.5-7.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '2','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '3','range' => '75-55','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '4','range' => '<55','created_at' => now()],
            // karet
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '2','range' => '2000-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '3','range' => '1500-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '4','range' => '<1500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '1','range' => '2500-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '2','range' => '3000-3500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '3','range' => '3500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '4','range' => '<4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '2','range' => '6.0- 6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '3','range' => '>6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '4','range' => 'tidak ada data','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '1','range' => '5.0-6.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '2','range' => '4.5-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '3','range' => '>4.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '4','range' => 'tidak ada data','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '2','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '3','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '4','range' => '<50','created_at' => now()],
            // kakao
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '1','range' => '1500-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '2','range' => '2000-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '3','range' => '3000-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '4','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '3','range' => '1250-1500','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '1','range' => '5.5-6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '2','range' => '6.5-7.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '3','range' => '7.5-8.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '4','range' => '<4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '2','range' => '5.0-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '3','range' => '4.5-5.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '1','range' => '<100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '2','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '3','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '4','range' => '<50','created_at' => now()],
            // Cengkeh
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '1','range' => '1500-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '2','range' => '2500-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '3','range' => '1250-1500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '4','range' => '>1250','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '3','range' => '3000-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '4','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '1','range' => '5.0-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '2','range' => '4.0-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '3','range' => '<4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '2','range' => '7.0-8.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '3','range' => '>8.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '2','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '3','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '4','range' => '<50','created_at' => now()],
            // Pala
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '1','range' => '2000-4500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '2','range' => '1800-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '4','range' => '<1800','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '2','range' => '4500-4800','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '4','range' => '>4800','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '1','range' => '5.0-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '2','range' => '4.0-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '3','range' => '>4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '2','range' => '7.0-8.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '3','range' => '>8.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '2','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '3','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '4','range' => '<50','created_at' => now()],
            // kayu manis
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '1','range' => '2000-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '2','range' => '1300-200','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '3','range' => '1000-1300','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '4','range' => '>1000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '2','range' => '2500-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '3','range' => '3000-4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '1','range' => '5.0-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '2','range' => '4.0-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '3','range' => '>4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '2','range' => '7.0-8.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '3','range' => '>8.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '2','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '3','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '4','range' => '<50','created_at' => now()],
            // kopi arabika
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '1','range' => '1200-1800','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '2','range' => '1000-1200','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '3','range' => '2000-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '4','range' => '>600','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '2','range' => '1800-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '3','range' => '800-1000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '4','range' => '>800','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '1','range' => '5.6-6.6','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '2','range' => '6.6-7.3','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '3','range' => '<5.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '3','range' => '<7.4','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '2','range' => '100-150','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '3','range' => '50-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '4','range' => '<50','created_at' => now()],
            // teh
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '1','range' => '2500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '2','range' => '4000-4500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '3','range' => '5000-6000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '4','range' => '>6000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '2','range' => '2500-1800','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '3','range' => '1800-1300','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '4','range' => '<1300','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '1','range' => '4.5-5.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '2','range' => '5.1-5.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '3','range' => '5.6-6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '4','range' => '>6.6','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '2','range' => '4.4-4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '3','range' => '3.9-3.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '4','range' => '<3.5','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '2','range' => '100-149','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '3','range' => '40-99','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '4','range' => '<40','created_at' => now()]
        ]);
    }
}
