<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SubkriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_subkriteria')->insert([
            // kopi robusta
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '1','loop' => '1','range' => '1500-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '3','loop' => '1','range' => '1250-1500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '4','loop' => '1','range' => '<1250','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '2','loop' => '2','range' => '2500-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '3','loop' => '2','range' => '3500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '1','id_kesesuaian' => '4','loop' => '2','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '1','loop' => '1','range' => '6.0-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '2','loop' => '1','range' => '5.5-6.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '3','loop' => '1','range' => '<5.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '2','loop' => '2','range' => '7.0-7.6','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '1','id_kesesuaian' => '3','loop' => '2','range' => '>7.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '1','loop' => '1','range' => '>125','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '2','loop' => '1','range' => '100-125','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '3','loop' => '1','range' => '60-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '1','id_kesesuaian' => '4','loop' => '1','range' => '<60','created_at' => now()],
            // Kelapa Sawit
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '1','loop' => '1','range' => '1700-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '2','loop' => '1','range' => '1450-1700','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '3','loop' => '1','range' => '1250-1450','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '4','loop' => '1','range' => '<1250','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '2','loop' => '2','range' => '2500-3500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '3','loop' => '2','range' => '3500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '2','id_kesesuaian' => '4','loop' => '2','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '1','loop' => '1','range' => '5.0-6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '2','loop' => '1','range' => '4.2-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '3','loop' => '1','range' => '>7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '2','id_kesesuaian' => '2','loop' => '2','range' => '6.5-7.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '1','loop' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '2','loop' => '1','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '3','loop' => '1','range' => '35-55','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '4','loop' => '1','range' => '>55','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '3','loop' => '2','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '2','id_kesesuaian' => '4','loop' => '2','range' => '<50','created_at' => now()],
            // karet
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '1','loop' => '1','range' => '2000-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '2','loop' => '1','range' => '1300-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '3','loop' => '1','range' => '1000-1300','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '4','loop' => '1','range' => '<1000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '2','loop' => '2','range' => '3000-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '3','loop' => '2','range' => '4000-5000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '3','id_kesesuaian' => '4','loop' => '2','range' => '>5000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '1','loop' => '1','range' => '5.2-7.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '2','loop' => '1','range' => '4.8-5.2','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '3','loop' => '1','range' => '<4.8','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '2','loop' => '2','range' => '7.5-8.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '3','id_kesesuaian' => '3','loop' => '2','range' => '>8.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '1','loop' => '1','range' => '>125','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '2','loop' => '1','range' => '100-125','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '3','loop' => '1','range' => '60-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '3','id_kesesuaian' => '4','loop' => '1','range' => '<60','created_at' => now()],
            // kakao
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '1','loop' => '1','range' => '2000-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '2','loop' => '1','range' => '1750-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '3','loop' => '1','range' => '1500-1750','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '4','loop' => '1','range' => '<1500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '2','loop' => '2','range' => '3000-3500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '3','loop' => '2','range' => '3500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '4','id_kesesuaian' => '4','loop' => '2','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '1','loop' => '1','range' => '5.3-6.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '2','loop' => '1','range' => '6.0-6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '3','loop' => '1','range' => '>6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '2','loop' => '2','range' => '5.0-5.3','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '4','id_kesesuaian' => '3','loop' => '2','range' => '<5.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '1','loop' => '1','range' => '>175','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '2','loop' => '1','range' => '125-175','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '3','loop' => '1','range' => '75-125','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '4','id_kesesuaian' => '4','loop' => '1','range' => '<75','created_at' => now()],
            // cengkeh
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '1','loop' => '1','range' => '2500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '2','loop' => '1','range' => '1800-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '3','loop' => '1','range' => '1300-1800','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '4','loop' => '1','range' => '<1300','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '2','loop' => '2','range' => '4000-5000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '3','loop' => '2','range' => '5000-6000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '5','id_kesesuaian' => '4','loop' => '2','range' => '>6000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '1','loop' => '1','range' => '4.5-5.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '2','loop' => '1','range' => '3.8-4.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '3','loop' => '1','range' => '<3.8','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '2','loop' => '2','range' => '5.5-5.8','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '5','id_kesesuaian' => '3','loop' => '2','range' => '>5.8','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '1','loop' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '2','loop' => '1','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '3','loop' => '1','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '5','id_kesesuaian' => '4','loop' => '1','range' => '<50','created_at' => now()],
            // pala
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '1','loop' => '1','range' => '2000-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '2','loop' => '1','range' => '2500-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '3','loop' => '1','range' => '3000-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '4','loop' => '1','range' => '<1500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '3','loop' => '2','range' => '1500-2000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '6','id_kesesuaian' => '4','loop' => '2','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '1','loop' => '1','range' => '5.0-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '2','loop' => '1','range' => '4.0-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '3','loop' => '1','range' => '<4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '2','loop' => '2','range' => '7.0-8.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '6','id_kesesuaian' => '3','loop' => '2','range' => '>8.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '1','loop' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '2','loop' => '1','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '3','loop' => '1','range' => '40-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '6','id_kesesuaian' => '4','loop' => '1','range' => '<40','created_at' => now()],
            // kayu manis
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '1','loop' => '1','range' => '1000-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '2','loop' => '1','range' => '2500-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '4','loop' => '1','range' => '>3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '2','loop' => '2','range' => '800-1000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '7','id_kesesuaian' => '4','loop' => '2','range' => '<800','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '1','loop' => '1','range' => '5.0-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '2','loop' => '1','range' => '4.0-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '3','loop' => '1','range' => '<4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '2','loop' => '2','range' => '7.0-8.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '7','id_kesesuaian' => '3','loop' => '2','range' => '>8.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '1','loop' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '2','loop' => '1','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '3','loop' => '1','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '7','id_kesesuaian' => '4','loop' => '1','range' => '<50','created_at' => now()],
            // kopi arabika
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '1','loop' => '1','range' => '1700-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '2','loop' => '1','range' => '1450-1700','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '3','loop' => '1','range' => '1250-1450','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '4','loop' => '1','range' => '<1250','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '2','loop' => '2','range' => '2500-3500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '3','loop' => '2','range' => '3500-4000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '8','id_kesesuaian' => '4','loop' => '2','range' => '>4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '1','loop' => '1','range' => '5.0-6.5','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '2','loop' => '1','range' => '4.2-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '3','loop' => '1','range' => '<4.2','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '2','loop' => '2','range' => '6.5-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '8','id_kesesuaian' => '3','loop' => '2','range' => '>7.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '1','loop' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '2','loop' => '1','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '3','loop' => '1','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '8','id_kesesuaian' => '4','loop' => '1','range' => '<50','created_at' => now()],
            // teh
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '1','loop' => '1','range' => '1500-2500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '2','loop' => '1','range' => '2500-3000','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '3','loop' => '1','range' => '1250-1500','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '4','loop' => '2','range' => '<1300','created_at' => now()],
            ['id_kriteria' => '1','id_tanaman' => '9','id_kesesuaian' => '3','loop' => '2','range' => '3000-4000','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '1','loop' => '1','range' => '5.0-7.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '2','loop' => '1','range' => '4.0-5.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '3','loop' => '1','range' => '<4.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '2','loop' => '2','range' => '7.0-8.0','created_at' => now()],
            ['id_kriteria' => '2','id_tanaman' => '9','id_kesesuaian' => '3','loop' => '2','range' => '>8.0','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '1','loop' => '1','range' => '>100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '2','loop' => '1','range' => '75-100','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '3','loop' => '1','range' => '50-75','created_at' => now()],
            ['id_kriteria' => '3','id_tanaman' => '9','id_kesesuaian' => '4','loop' => '1','range' => '<50','created_at' => now()],
        ]);
    }
}
